EFFECTS = {
    "STANDARD": {"friendly_name": "Standard", "styleName": "FOLLOW_VIDEO"},
    "NATURAL": {"friendly_name": "Natural", "styleName": "FOLLOW_VIDEO"},
    "IMMERSIVE": {"friendly_name": "Sports", "styleName": "FOLLOW_VIDEO"},
    "VIVID": {"friendly_name": "Vivid", "styleName": "FOLLOW_VIDEO"},
    "GAME": {"friendly_name": "Game", "styleName": "FOLLOW_VIDEO"},
    "COMFORT": {"friendly_name": "Comfort", "styleName": "FOLLOW_VIDEO"},
    "RELAX": {"friendly_name": "Relax", "styleName": "FOLLOW_VIDEO"},
    "VU_METER": {"friendly_name": "Retro", "styleName": "FOLLOW_AUDIO"},
    "ENERGY_ADAPTIVE_BRIGHTNESS": {
        "friendly_name": "Lumina",
        "styleName": "FOLLOW_AUDIO",
    },
    "ENERGY_ADAPTIVE_COLORS": {"friendly_name": "Colora", "styleName": "FOLLOW_AUDIO"},
    "SPECTRUM_ANALYSER": {"friendly_name": "Spectrum", "styleName": "FOLLOW_AUDIO"},
    "KNIGHT_RIDER_CLOCKWISE": {
        "friendly_name": "Scanner - Clockwise",
        "styleName": "FOLLOW_AUDIO",
    },
    "KNIGHT_RIDER_ALTERNATING": {
        "friendly_name": "Scanner - Alternating",
        "styleName": "FOLLOW_AUDIO",
    },
    "RANDOM_PIXEL_FLASH": {"friendly_name": "Rhythm", "styleName": "FOLLOW_AUDIO"},
    "MODE_RANDOM": {"friendly_name": "Random", "styleName": "FOLLOW_AUDIO"},
    "HOT_LAVA": {"friendly_name": "Hot Lava", "styleName": "FOLLOW_VIDEO"},
    "DEEP_WATER": {"friendly_name": "Deep Water", "styleName": "FOLLOW_VIDEO"},
    "FRESH_NATURE": {"friendly_name": "Fresh Nature", "styleName": "FOLLOW_VIDEO"},
    "ISF": {"friendly_name": "Warm White", "styleName": "FOLLOW_VIDEO"},
    "CUSTOM_COLOR": {"friendly_name": "Custom Color", "styleName": "FOLLOW_VIDEO"},
}
